name: Continuous Training
on:
  push:
    branches:
      - workflow_continuous_training
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for training'
        required: false
        default: running CT
jobs:
  continuous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip3 install -r requirements_test.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl.dvc -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Training Completed"
          dvc add model/model.pkl -r model-track --to-remote
          dvc push model/model.pkl.dvc -r model-track

      - name: Commit .dvc file change
        run: |
          git config --local user.email "kyfunky1386@gmail.com"
          git config --local user.name "github-actions-bot"
          git add model/model.pkl.dvc
          git commit -m "CT: Update model.pkl.dvc"

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: iterative/setup-cml@v1

      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          cml-publish prediction_behavior.png -md >> report.md
          cml-send-comment report.md




