name: Continuous Training

on:
  push:
    branches:
      - workflow_continuous_training
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for training'
        required: false
        default: running CT

jobs:
  continuous-training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requeriments_test.txt

      - name: Set up Google Cloud credentials
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo $SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/gcloud.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json

      - name: Pull and repro model
        run: |
          source venv/bin/activate
          dvc pull model/model.pkl.dvc -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Training Completed"

      - name: Add and push model to DVC remote
        run: |
          source venv/bin/activate
          dvc add model/model.pkl
          dvc push -r model-track

      - name: Commit .dvc file change
        run: |
          git config --local user.email "kyfunky1386@gmail.com"
          git config --local user.name "github-actions-bot"
          git add model/model.pkl.dvc
          git commit -m "CT: Update model.pkl.dvc"
      
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          cml-publish prediction_behavior.png -md >> report.md
          cml-send-comment report.md




