name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setting up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Installing dependencies
        run: |
          source venv/bin/activate
          pip install dvc[gs]
          pip install -r requirements_test.txt

      - name: Set up Google Cloud credentials
        run: |
          source venv/bin/activate
          python setter.py
          export GOOGLE_APPLICATION_CREDENTIALS=$(python -c "import os; print(os.path.realpath('path.json'))")
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Pull DVC data
        run: |
          source venv/bin/activate
          dvc pull model/model.pkl -r model-track

      - name: Test API
        run: |
          source venv/bin/activate
          pytest test.py
